module.exports.paths = {
  public: __dirname+'/../assets' // or wherever
}
module.exports.routes = {
  '/auth': '/?route=auth',
  '/persons/edit/:id': 'PersonsController.edit',
  '/persons/set-fields': 'PersonsController.setFields',
  '/salaryrules/export-data': 'SalaryRulesController.exportData',
  '/salaryrules/edit/:id': 'SalaryRulesController.edit',
  '/salaryrules/delete/:id': 'SalaryRulesController.delete',
  '/groups/general-default-instructors': 'GroupsController.generalDefaultInstructors',
  '/instructors/edit/:id': 'InstructorsController.edit',
  '/groups/edit/:id': 'GroupsController.edit',
  '/groups/delete/:id': 'GroupsController.delete',
  '/groups/sheet/:id': 'GroupsController.sheet',
  '/groups/detail/:id': 'GroupsController.detail',
  '/groups/instructor-detail/:id': 'GroupsController.instructorDetail',
  '/groups/instructor-groups/:id': 'GroupsController.instructorGroups',
  '/groups/instructor-schedule-calendar/:id': 'GroupsController.instructorScheduleCalendar',
  '/groups/add-person/:id': 'GroupsController.addPerson',
  '/groups/add-persons/:id': 'GroupsController.addPersons',
  '/groups/remove-person/:id': 'GroupsController.removePerson',
  '/groups/export': 'GroupsController.exportReport',
  '/groups/auto-debit': 'GroupsController.autoDebit',
  '/groups/export-personals': 'GroupsController.exportPersonals',
  '/events/edit/:id': 'EventsController.edit',
  '/events/delete/:id': 'EventsController.delete',
  '/events/add-visitor/:id': 'EventsController.addVisitor',
  '/events/remove-visitor/:id': 'EventsController.removeVisitor',
  '/payments/edit/:id': 'PaymentsController.edit',
  '/payments/delete/:id': 'PaymentsController.delete',
  '/payments/create-all': 'PaymentsController.createAll',
  '/payments/group-unpayed-events': 'PaymentsController.groupUnpayedEvents',
  '/incomes/edit/:id': 'IncomesController.edit',
  '/incomes/delete/:id': 'IncomesController.delete',
  '/reports/export-visits': 'ReportsController.exportVisits',
  '/reports/export-instructors': 'ReportsController.exportInstructors',
  '/reports/export-transactions': 'ReportsController.exportTransactions',
  '/reports/export-totals': 'ReportsController.exportTotals',
  '/reports/export-activity': 'ReportsController.exportActivity',
  '/dashboard/month-info': 'DashboardController.monthInfo',
  '/dashboard/create-month-events': 'DashboardController.createMonthEvents',
  '/users/edit/:id': 'UsersController.edit',
  '/users/delete/:id': 'UsersController.delete',
  '/users/get-password': 'UsersController.getPassword',
  '/cp*': function(req, res) { return res.redirect('/?route=' + req.url.substr(1)) },
};
