module.exports.paths = {
  public: __dirname+'/../assets' // or wherever
}
module.exports.routes = {
  '/auth': '/?route=auth',
  '/club': '/?route=club',
  '/galery': '/?route=galery',
  '/tournaments': '/?route=tournaments',
  '/boss': '/?route=boss',
  '/halls': '/?route=halls',
  '/feedback': '/?route=feedback',
  '/contacts': '/?route=contacts',
  '/instructors': '/?route=instructors',
  '/groups': '/?route=groups',
  '/schedule': '/?route=schedule',
  '/privacy': '/?route=privacy',
  '/profile': '/?route=profile',
  '/prices': '/?route=prices',
  '/data-transport': '/?route=data-transport',
  '/service-rules': '/?route=service-rules',
  '/payment-methods': '/?route=payment-methods',
  '/self-payments': '/?route=self-payments',
  '/self-schedule': '/?route=self-schedule',
  '/persons/edit/:id': 'PersonsController.edit',
  '/persons/set-fields': 'PersonsController.setFields',
  '/archivepersons/edit/:id': 'ArchivePersonsController.edit',
  '/archivepersons/delete/:id': 'ArchivePersonsController.delete',
  '/salaryrules/export-data': 'SalaryRulesController.exportData',
  '/salaryrules/edit/:id': 'SalaryRulesController.edit',
  '/salaryrules/delete/:id': 'SalaryRulesController.delete',
  '/groups/general-default-instructors': 'GroupsController.generalDefaultInstructors',
  '/places/edit/:id': 'PlacesController.edit',
  '/groups/edit/:id': 'GroupsController.edit',
  '/groups/delete/:id': 'GroupsController.delete',
  '/groups/sheet/:id': 'GroupsController.sheet',
  '/groups/detail/:id': 'GroupsController.detail',
  '/groups/instructor-detail/:id': 'GroupsController.instructorDetail',
  '/groups/instructor-groups/:id': 'GroupsController.instructorGroups',
  '/groups/instructor-schedule-calendar/:id': 'GroupsController.instructorScheduleCalendar',
  '/groups/add-person/:id': 'GroupsController.addPerson',
  '/groups/add-persons/:id': 'GroupsController.addPersons',
  '/groups/remove-person/:id': 'GroupsController.removePerson',
  '/groups/export-generals': 'GroupsController.exportGenerals',
  '/groups/export-personals': 'GroupsController.exportPersonals',
  '/events/edit/:id': 'EventsController.edit',
  '/events/delete/:id': 'EventsController.delete',
  '/events/add-visitor/:id': 'EventsController.addVisitor',
  '/events/remove-visitor/:id': 'EventsController.removeVisitor',
  '/payments/edit/:id': 'PaymentsController.edit',
  '/payments/delete/:id': 'PaymentsController.delete',
  '/payments/create-all': 'PaymentsController.createAll',
  '/payments/self-create-all': 'PaymentsController.selfCreateAll',
  '/payments/group-unpayed-events': 'PaymentsController.groupUnpayedEvents',
  '/payments/self-group-unpayed-events': 'PaymentsController.selfGroupUnpayedEvents',
  '/payments/self-settings': 'PaymentsController.selfSettings',
  '/payments/self-transactions': 'PaymentsController.selfTransactions',
  '/incomes/edit/:id': 'IncomesController.edit',
  '/incomes/delete/:id': 'IncomesController.delete',
  '/dashboard/export-visits': 'DashboardController.exportVisits',
  '/dashboard/export-instructors': 'DashboardController.exportInstructors',
  '/dashboard/export-payments': 'DashboardController.exportPayments',
  '/dashboard/export-totals': 'DashboardController.exportTotals',
  '/dashboard/month-info': 'DashboardController.monthInfo',
  '/dashboard/create-month-events': 'DashboardController.createMonthEvents',
  '/materials/edit/:id': 'MaterialsController.edit',
  '/materials/delete/:id': 'MaterialsController.delete',
  '/users/edit/:id': 'UsersController.edit',
  '/users/delete/:id': 'UsersController.delete',
  '/users/get-password': 'UsersController.getPassword',
  '/files/edit/:id': 'FilesController.edit',
  '/files/delete/:id': 'FilesController.delete',
  '/site/uploads*': 'SiteController.uploads',
  '/site/public-schedule': 'SiteController.publicSchedule',
  '/site/self-schedule': 'SiteController.selfSchedule',
  '/site/profile-person': 'SiteController.profilePerson',
  '/cp*': function(req, res) { return res.redirect('/?route=' + req.url.substr(1)) },
  '/articles*': function(req, res) { return res.redirect('/?route=' + req.url.substr(1)) },
};
